(PAYM-662)All github actions commonly used in our repos
tesourohq/Tesouro-Github-Actions pull request #1
Opened 2022-07-22 22:42 UTC by ali-tesouro

2022-07-23 14:46 UTC, Tesouro-Chris reviewed
Just a friendly callout as to a few things that still need to be parameterized.

2022-07-23 14:46 UTC, Tesouro-Chris commented on build-docker-images/action.yml
> +        file: ./src/Tesouro.Payments.Service.CardProcessing/Dockerfile
I believe these needs to be parameters as well

2022-07-23 14:46 UTC, Tesouro-Chris commented on create-sdk/action.yml
> +      run: yardarm generate -i ./test/tests/bin/results/updates/swagger.json --nupkg ./dist/ -n Tesouro.Payments.Service.CardProcessing.SDK -v ${{ inputs.nuget-version }} -x Yardarm.SystemTextJson --
I believe the SDK name needs to be parameterized as well

2022-07-23 14:46 UTC, Tesouro-Chris commented on functional-tests/action.yml
> +        UNDERTEST_IMAGE: "gcr.io/tesouro-cloud/tesouro-service-card-processing${{ github.event_name == 'pull_request' && '-ci' || '' }}:${{ inputs.sem-ver }}"
I believe this needs to be parameterized

2022-07-23 14:46 UTC, Tesouro-Chris commented on notify-spinnaker/action.yml
> +          }
These need to be parameterized as well

2022-07-25 15:44 UTC, ali-tesouro commented on build-docker-images/action.yml
> +        file: ./src/Tesouro.Payments.Service.CardProcessing/Dockerfile
Good catch!

2022-07-25 15:46 UTC, ali-tesouro commented on create-sdk/action.yml
> +      run: yardarm generate -i ./test/tests/bin/results/updates/swagger.json --nupkg ./dist/ -n Tesouro.Payments.Service.CardProcessing.SDK -v ${{ inputs.nuget-version }} -x Yardarm.SystemTextJson --
I forgot to review when I extracted actions to review everything. Sorry about the oversight. I think I left the review for later and then I forgot to extract all variables after the proof of concept.

2022-07-26 16:40 UTC, nbenmoody-tesouro requested changes

2022-07-26 16:40 UTC, nbenmoody-tesouro commented on build-and-test/action.yml
> +        dotnet nuget add source --username USERNAME --password ${{ inputs.gh-packages-token }} --store-password-in-clear-text --name github https://nuget.pkg.github.com/tesourohq/index.json
Will these actions post logs to the public repo?

2022-07-26 16:40 UTC, nbenmoody-tesouro commented on build-and-test/action.yml
> +        dotnet nuget add source --username USERNAME --password ${{ inputs.gh-packages-token }} --store-password-in-clear-text --name github https://nuget.pkg.github.com/tesourohq/index.json
Just curious if any sensitive inputs may somehow leak through.

2022-07-26 16:40 UTC, nbenmoody-tesouro commented on build-docker-images/action.yml
> +        service_account: spinnaker-gcr-account@tesouro-cloud.iam.gserviceaccount.com
Can this be parametrized and passed in, instead of sitting in public?

2022-07-26 16:40 UTC, nbenmoody-tesouro commented on functional-tests/action.yml
> +        service_account: spinnaker-gcr-account@tesouro-cloud.iam.gserviceaccount.com
Parameterize?

2022-07-26 17:01 UTC, ali-tesouro commented on build-and-test/action.yml
> +        dotnet nuget add source --username USERNAME --password ${{ inputs.gh-packages-token }} --store-password-in-clear-text --name github https://nuget.pkg.github.com/tesourohq/index.json
https://user-images.githubusercontent.com/101150630/181066623-aeb4622d-11a6-4801-8223-297aefa46143.png

2022-07-26 19:55 UTC, nbenmoody-tesouro approved these changes

2022-07-26 20:25 UTC, merged